definitions:
 - &jdk-image
   image_resource:
     type: registry-image
     source:
       repository: openjdk
       tag: 11

 - &pcf-source-details
   api: https://api.run.pivotal.io
   Username: rfang@pivotal.io
   Password: <replacement2>
   organization: sashin-org

resources:
 - name: repo
   type: git
   source:
     uri: https://github.com/raymond700620/rps.git
     branch: master

 - name: pws-dev
   type: cf
   source:
     <<: *pcf-source-details
     space: rfang@pivotal.io

jobs:
 - name: rps
   plan:
     - get: repo
       trigger: true
     - task: rps-build
       config:
         <<: *jdk-image
         platform: linux
         inputs:
           - name: repo
         outputs:
           - name: build
         run:
           path: sh
           args:
             - -exc
             - |
               export M2_HOME=$(pwd)/.m2
               cd repo/
               ./gradlew build
               cp build/libs/*.jar ../build/
         caches:
           - path: .gradle/
           - path: .m2/
     - put: pws-dev
       params:
         manifest: repo/manifest.yml
         path: build/*.jar